# Generated by Django 3.1.2 on 2020-10-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_curso', models.CharField(max_length=100)),
                ('codigo_do_curso', models.IntegerField()),
            ],
        ),
    ]
