# Generated by Django 3.1.2 on 2020-10-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0004_auto_20201027_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='curso_organizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestoreventos.curso'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_final',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
