# Generated by Django 3.1.2 on 2020-10-27 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0005_auto_20201027_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestoreventos.funcionario'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='palestrantes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestoreventos.palestrante'),
        ),
    ]
