# Generated by Django 3.1.4 on 2020-12-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0007_auto_20201116_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nome_do_curso',
            new_name='nome_curso',
        ),
    ]
