# Generated by Django 3.1.4 on 2020-12-07 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestoreventos', '0008_auto_20201207_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
            preserve_default=False,
        ),
    ]
