# Generated by Django 3.1.3 on 2020-11-16 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestoreventos', '0006_auto_20201027_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nome_curso',
            new_name='nome_do_curso',
        ),
        migrations.AlterField(
            model_name='evento',
            name='curso_organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestoreventos.curso'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_final',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestoreventos.funcionario'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='palestrantes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestoreventos.palestrante'),
        ),
    ]
