# Generated by Django 2.2.6 on 2019-10-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_add', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TesteMigrateMaluco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myteste', models.CharField(max_length=500)),
            ],
        ),
    ]
