# Generated by Django 2.2.6 on 2019-10-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa_sugestoes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TesteMigrateMaluco',
        ),
    ]
