# Generated by Django 2.2.6 on 2019-11-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_assunto', models.CharField(max_length=100)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
